author: []
date: ''
doctitle: 'Appendix I: Application Level Gateway (ALG) and Port Forwarding List'
subtitle: ''
title: 'Appendix I: Application Level Gateway (ALG) and Port Forwarding List'
titleid: 'sec:application-level-gateway-alg-and-port-forwarding-list'
