author: []
date: ''
doctitle: 'Appendix III: Routed Architecture – Examples of Potential Configurations'
subtitle: ''
title: 'Appendix III: Routed Architecture – Examples of Potential Configurations'
titleid: 'sec:routed-architecture-examples-of-potential-configurations'
