author: []
date: ''
doctitle: 'Appendix IV: Bridged Architecture – Examples of Potential Configurations'
subtitle: ''
title: 'Appendix IV: Bridged Architecture – Examples of Potential Configurations'
titleid: 'sec:bridged-architecture-examples-of-potential-configurations'
